apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-host
  annotations:
    kubernetes.io/ingress.class: "nginx"
    #cert-manager.io/cluster-issuer: "letsencrypt"
    #ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  rules:
  - host: "www.agrownegocios.dev.br"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          serviceName: svc-frontend
          servicePort: 80
#  tls:
#  - hosts:
#    - "www.agrownegocios.dev.br"
#    secretName: letsencrypt-tls 