apiVersion: awspca.cert-manager.io/v1beta1
kind: AWSPCAClusterIssuer
metadata:
  name: demo-test-root-ca
spec:
  arn: arn:aws:acm:us-west-1:455213735070:certificate/28cbdd95-60a7-48f8-97ed-fe739bdd4206
  region: us-west-1