apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-hosts
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: "www.agrownegocios.dev.br"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: svc-frontend
            port:
              number: 80