apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-sigescom-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend-sigescom
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resources
      resource:
        name: cpu
        target:
          type: utilization
          averageUtilization: 50