apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-hosts
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # cert-manager.io/cluster-issuer: "letsencrypt"
    # ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  rules:
  - host: "www.agrownegocios.dev.br"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: svc-frontend-sigescom
            port:
              number: 80
  - host: "backend.agrownegocios.dev.br"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: svc-backend
            port:
              number: 8080
  # tls:
  # - hosts:
  #   - "www.agrownegocios.dev.br"
  #   secretName: letsencrypt