apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-sigescom-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend-sigescom
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 25