apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: "backend"
    spec:
      containers:
        - name: backend-container
          image: agrownegocios/backend:v335
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "1.5Gi" #(37,5%)
              cpu: "750m" #1vCpu = 1000 (37,5%)
      nodeSelector:
        disktype: node-agrow-backend
      imagePullSecrets:
        - name: regcred

