apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: "backend"
    spec:
      containers:
        - name: backend-container
          image: agrownegocios/backend:v300
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "2Gi"
              cpu: "1000m"
      nodeSelector:
        disktype: node-agrow-backend
      imagePullSecrets:
        - name: regcred

