apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: "backend"
    spec:
      containers:
        - name: backend-container
          image: agrownegocios/backend:v280.02
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "0.35"
              memory: 20Mi
            limits:
              cpu: "0.75"
              memory: 50Mi
      imagePullSecrets:
        - name: regcred
