apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: "backend"
    spec:
      containers:
        - name: backend-container
          image: agrownegocios/backend:v1
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: backend-configmap
      imagePullSecrets:
        - name: regcred