apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: "backend"
    spec:
      containers:
        - name: backend-container
          image: agrownegocios/backend:v273.01
          ports:
            - containerPort: 8080
           resources:
            requests:
              cpu: "0.75"
      imagePullSecrets:
        - name: regcred