apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- frontend.yaml

images:
- name: frontend
  newName: agrownegocios/frontend-adm
  newTag: fb95c9dc1493b77f592e605a53883ac3821c8aaa
