apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: "backend"
    spec:
      containers:
        - name: backend-container
          image: agrownegocios/backend-teste:v296
          ports:
            - containerPort: 8080
          resources:
             requests:
              memory: 100M
              cpu: 0.3
      nodeSelector:
        disktype: node-homologacao-backend
      imagePullSecrets:
        - name: regcred
