apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- svc.yaml

images:
- name: frontend-img
  newName: agrownegocios/frontend-adm
  newTag: f9b216022277d355253ba57a9031942349fe5490
