apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml

images:
- name: frontend
  newName: agrownegocios/frontend-adm
  newTag: e6643a9109b841bda8f8354b3fa755264d66bf9a
